name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Pega o código do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      # Configura o buildx (necessário pro build multi-plataforma e cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build e Push da imagem
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gabriel033/kube-news:latest
            gabriel033/kube-news:${{github.run_number}}

