# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Autenticação Docker Hub
      uses: docker/login-action@v3.5.0
      with:
       username: ${{secrets.DOCKER_USER}}
       password: ${{secrets.DOCKER_PWD}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       tags: |
         gabrielfernandes/kube-news:0.0.1
         gabrielfernandes/kube-news:latest
