# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Construção da imagem Docker
      uses: docker/build-push-action@v6.18.0
      with:
       context : ./src
       file: ./src/Dockerfile
       push: true
       tags:
        gabrielfernandes/kube-news:RELEASE 0.0.1
        gabrielfernandes/kube-news:latest
